# -*- coding: utf-8 -*-
"""Netflix_Analysis_Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/144WmmV-Ju4ym948QeHstDKfwV2KMlitf
"""

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")

print("Dataset loaded!")
print(df.shape)
print(df.head())
print(df.columns)

import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df = pd.read_csv(url)

print("="*50)
print("DATASET INFO")
print("="*50)
print(f"Shape: {df.shape}")
print(f"\nColumns: {df.columns.tolist()}")
print(f"\nData Types:\n{df.dtypes}")
print(f"\nMissing Values: {df.isnull().sum().sum()}")

print("\n" + "="*50)
print("BASIC STATISTICS")
print("="*50)
print(df.describe())

print("\n" + "="*50)
print("SPECIES COUNT")
print("="*50)
print(df['species'].value_counts())

print("\n" + "="*50)
print("AVERAGE MEASUREMENTS BY SPECIES")
print("="*50)
print(df.groupby('species')[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].mean())

import pandas as pd

df_netflix = pd.read_csv("https://raw.githubusercontent.com/mdfahimabid/netflix-dataset/main/titles.csv")

print("="*50)
print("NETFLIX DATASET")
print("="*50)
print(f"Shape: {df_netflix.shape}")
print(f"\nColumns: {df_netflix.columns.tolist()}")
print(f"\nFirst 5 rows:")
print(df_netflix.head())

print("\n" + "="*50)
print("BASIC INFO")
print("="*50)
print(df_netflix.info())

print("\n" + "="*50)
print("MISSING VALUES")
print("="*50)
print(df_netflix.isnull().sum())

import pandas as pd
import numpy as np

data = {
    'show_id': ['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8'],
    'title': ['Breaking Bad', 'The Crown', 'Stranger Things', 'DARK', 'Narcos', 'The Office', 'Friends', 'The Witcher'],
    'type': ['TV Show', 'TV Show', 'TV Show', 'TV Show', 'TV Show', 'TV Show', 'TV Show', 'TV Show'],
    'release_year': [2008, 2016, 2016, 2017, 2015, 2005, 1994, 2019],
    'country': ['United States', 'United Kingdom', 'United States', 'Germany', 'Colombia', 'United States', 'United States', 'Poland'],
    'duration': ['49 min', '58 min', '50 min', '55 min', '50 min', '22 min', '24 min', '60 min']
}

df_netflix = pd.DataFrame(data)

print("="*50)
print("NETFLIX ANALYSIS")
print("="*50)
print(f"Total Titles: {len(df_netflix)}")
print(f"\nMovies vs Shows:")
print(df_netflix['type'].value_counts())
print(f"\nRelease Year Range: {df_netflix['release_year'].min()} - {df_netflix['release_year'].max()}")
print(f"\nTop Countries:")
print(df_netflix['country'].value_counts())
print(f"\nDataset:")
print(df_netflix)

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

df_netflix['release_year'].hist(ax=axes[0], bins=10)
axes[0].set_title('Content by Year')
axes[0].set_xlabel('Year')

df_netflix['country'].value_counts().plot(kind='barh', ax=axes[1])
axes[1].set_title('Top Countries')

plt.tight_layout()
plt.show()